### ISSUE TITLE
Could not import "package:angel/angel.dart"

### ISSUE THREAD

**Issue by jkleiser** [angel-dart/example_file_upload#1]
I cloned this example, then did a `pub get` and a `bin/server.dart`. Then I get this:
```
Unhandled exception:
Could not import "package:angel/angel.dart" from "file:///Volumes/P3/Angel/example_file_upload/bin/server.dart": No mapping for 'angel' package when resolving 'package:angel/angel.dart'.
null
```
I have also tried to follow the instructions in your blog post, but when I try `bin/server.dart` there, I get this:
```
Unhandled error occurred: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 59074
#0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _rootRunBinary (dart:async/zone.dart:1170)
...
```

**Comment by thosakwe** [comment]
Sorry, still working on some refactorings, and this is a result of that. In
a few days, you'll be ready to try Angel out. :)

**Comment by thosakwe** [comment]
@jkleiser I finished upgrading the [router](https://github.com/angel-dart/route) (This was actually an enormous change), and on a closer look, it looks like the problems you had are actually not related to Angel.

The first looks like pub's error, while the other is a MongoDB connection error.

**Comment by thosakwe** [comment]
Ah, I see what was wrong. Angel expects your project to be named `angel`, and I forgot that.

In the [CLI tool](https://github.com/angel-dart/cli), I'll eventually add an option to rename your project

Resolved with https://github.com/angel-example/file_upload/commit/8f28013c18fd987c39eeb56fdd4756a4131a37d4.
